[Writable]
  LogLevel = "INFO"
  [Writable.Pipeline]
    ExecutionOrder = "HTTPPost"

    [Writable.Pipeline.Functions.FilterByDeviceName]
      [Writable.Pipeline.Functions.FilterByDeviceName.Parameters]
        DeviceNames = ""
    [Writable.Pipeline.Functions.FilterByValueDescriptor]
      [Writable.Pipeline.Functions.FilterByValueDescriptor.Parameters]
        ValueDescriptors = ""
    [Writable.Pipeline.Functions.HTTPPost]
      [Writable.Pipeline.Functions.HTTPPost.Parameters]
        url = "http://"
        mimeType = "" #OPTIONAL - default application/json

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = "10s"
Host = "localhost"
Port = 50003
Protocol = "http"
ReadMaxLimit = 100
StartupMsg = "AppServiceConfigurable-http-export has Started"
Timeout = 5000

[Registry]
Host = "localhost"
Port = 8500
Type = "consul"

[Clients]
  [Clients.CoreData]
  Protocol = "http"
  Host = "localhost"
  Port = 48080

  [Clients.Logging]
  Protocol = "http"
  Host = "localhost"
  Port = 48061

[Binding]
Type="messagebus"
SubscribeTopic="events"

[MessageBus]
Type = "zero"
    [MessageBus.SubscribeHost]
        Host = "localhost"
        Port = 5563
        Protocol = "tcp"

[Logging]
EnableRemote = false
File = "./logs/app-service-configurable-http-export.log"