[Writable]
  LogLevel = "INFO"

  [Writable.StoreAndForward]
    Enabled = false
    RetryInterval = 300000 # 5mins in milliseconds
    MaxRetryCount = 10

  [Writable.Pipeline]
    ExecutionOrder = "FilterByDeviceName, TransformToJSON, HTTPPostJSON, MarkAsPushed"

    [Writable.Pipeline.Functions.TransformToJSON]
    [Writable.Pipeline.Functions.MarkAsPushed]
    [Writable.Pipeline.Functions.FilterByDeviceName]
      [Writable.Pipeline.Functions.FilterByDeviceName.Parameters]
        DeviceNames = ""
    [Writable.Pipeline.Functions.FilterByValueDescriptor]
      [Writable.Pipeline.Functions.FilterByValueDescriptor.Parameters]
        ValueDescriptors = ""
    [Writable.Pipeline.Functions.HTTPPostJSON]
      [Writable.Pipeline.Functions.HTTPPostJSON.Parameters]
        url = "http://"
        persistOnError = "false"

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = "10s"
Host = "app-service-configurable-http-export"
Port = 48095
Protocol = "http"
ReadMaxLimit = 100
StartupMsg = "AppServiceConfigurable-http-export has Started"
Timeout = 5000

[Registry]
Host = "edgex-core-consul"
Port = 8500
Type = "consul"

[Database]
Type = "mongodb"
Host = "edgex-mongo"
Port = 27017
Timeout = 5000
Username = "application-service"
Password = "password"

[Clients]
  [Clients.CoreData]
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080

  [Clients.Logging]
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Binding]
Type="messagebus"
SubscribeTopic="events"

[MessageBus]
Type = "zero"
    [MessageBus.SubscribeHost]
        Host = "edgex-core-data"
        Port = 5563
        Protocol = "tcp"

[Logging]
EnableRemote = true