[Writable]
  LogLevel = "INFO"
  [Writable.Pipeline]
    ExecutionOrder = "SetOutputData"

    [Writable.Pipeline.Functions.SetOutputData]
    [Writable.Pipeline.Functions.FilterByDeviceName]
      [Writable.Pipeline.Functions.FilterByDeviceName.Parameters]
        DeviceNames = ""
    [Writable.Pipeline.Functions.FilterByValueDescriptor]
      [Writable.Pipeline.Functions.FilterByValueDescriptor.Parameters]
        ValueDescriptors = ""

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = "10s"
Host = "app-service-configurable-rules-engine"
Port = 48095
Protocol = "http"
ReadMaxLimit = 100
StartupMsg = "AppServiceConfigurable-rules-engine has Started"
Timeout = 5000

[Registry]
Host = "edgex-core-consul"
Port = 8500
Type = "consul"

[Clients]
  [Clients.CoreData]
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080

  [Clients.Logging]
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Binding]
Type="messagebus"
SubscribeTopic="events"
PublishTopic=""

[MessageBus]
Type = "zero"
    [MessageBus.SubscribeHost]
        Host = "edgex-core-data"
        Port = 5563
        Protocol = "tcp"
    [MessageBus.PublishHost]
        Host = "*"
        Port = 5566
        Protocol = "tcp"

[Logging]
EnableRemote = true